#########################################################
#
# Create a Github Release
# Publish to npm
#
#########################################################

name: Release

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on


jobs:
  release:
    name: Release to GitHub and npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # see: https://github.com/pnpm/action-setup for how to use cache
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"


      - name: Install dependencies
        run: pnpm install --fix-lockfile

      
      - name: Release to GH and NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
